version: '26'
services:
  scrapy:
    build: .
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
  mongo: # Optional
    image: mongo
  redis: # Optional
    image: redis
