version: '26'
services:
  scrapy:
    build: .
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    depends_on:
      - postgres
      - redis
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379

      
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres_data: